import { Toaster } from "~/components/ui/toaster";
import { DataProvider } from "~/context/DataContext";
import { ReactQueryProvider } from "~/lib/ReactQueryProvider";
import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Search Band App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <DataProvider>{children}</DataProvider>
          <Toaster />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
